# config/config.yaml
# Example configuration for MQTT broker and smart devices

mqtt:
  broker: tcp://localhost:1883
  username: user
  password: pass

lights:
  - id: "living-room"
    type: "tasmota"
    topic: "cmnd/livingroom/POWER"

outlets:
  - id: "tv-outlet"
    type: "tasmota"
    topic: "cmnd/tvoutlet/POWER"

thermostats:
  - id: "downstairs"
    model: "honeywell_t5+"
    mac_id: "5C:FC:E1:7C:24:06"

  - id: "upstairs"
    model: "honeywell_t5+"
    mac_id: "5C:FC:E1:7C:21:0E"
